Linkar menu section
iwtrainingbr/site-front-08 pull request #30
Opened 2021-07-14 00:50 UTC by La017

resolve #21

2021-07-14 01:03 UTC, Phytion1318 requested changes

2021-07-14 01:03 UTC, Phytion1318 commented on index.html
> +              <a class="nav-link" href="#contrato">Contato</a>
Linha 35:
Tá escrito "Contrato" no lugar de "Contato"

2021-07-14 01:03 UTC, La017 commented on index.html
> +              <a class="nav-link" href="#contrato">Contato</a>
corrigido meu CHAPAAAAAAAAA

2021-07-15 19:23 UTC, Phytion1318 requested changes
Trocar o "Contrato" por "Contato" na linha 35

2021-07-15 19:23 UTC, Phytion1318 commented on index.html
> +              <a class="nav-link" href="#contrato">Contato</a>
Ainda está escrito "Contrato" ao invés de "Contato"
![image](https://user-images.githubusercontent.com/87044711/125845507-dfc1717a-bfa5-4c30-a18f-7597f757a793.png)

2021-07-16 01:21 UTC, Phytion1318 approved these changes

2021-07-16 17:57 UTC, alessandrofeitoza approved these changes

2021-07-16 17:57 UTC, merged